[package]
name = "sandblaster"
version = "0.1.0"
authors = ["Isaac Lewis <isaac@ike.io>"]

[dependencies]
reqwest = "0.9.18"
clap = {version = "2.33.0", features = ["yaml"]}
regex = "0.2"

[features]
default = []
